Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig,axs = plt.subplots(2, 3,figsize=(15,8))
for i,name_train,name_test in zip ([0,1,2],fichiers_train,fichiers_test):
    train_data,train_labels = extract_data(name_train)
    test_data, test_labels = extract_data(name_test)

    model = Perceptron(train_data.shape[1])
    optimizer = optim.Adam(model.parameters())
    pltloss,acc = train_session(torch.FloatTensor(train_data),torch.FloatTensor(train_labels),model,loss,optimizer)
    
    titre= "PrÃ©cision ={0:5.3f} ".format(acc)
    plotResults(axs[0][i],axs[1][i],test_data, test_labels, model, titre, pltloss, name_test)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[7], line 11[0m
[1;32m      8[0m pltloss,acc [38;5;241m=[39m train_session(torch[38;5;241m.[39mFloatTensor(train_data),torch[38;5;241m.[39mFloatTensor(train_labels),model,loss,optimizer)
[1;32m     10[0m titre[38;5;241m=[39m [38;5;124m"[39m[38;5;124mPrÃ©cision =[39m[38;5;132;01m{0:5.3f}[39;00m[38;5;124m [39m[38;5;124m"[39m[38;5;241m.[39mformat(acc)
[0;32m---> 11[0m [43mplotResults[49m[43m([49m[43maxs[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m[[49m[43mi[49m[43m][49m[43m,[49m[43maxs[49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m[43m[[49m[43mi[49m[43m][49m[43m,[49m[43mtest_data[49m[43m,[49m[43m [49m[43mtest_labels[49m[43m,[49m[43m [49m[43mmodel[49m[43m,[49m[43m [49m[43mtitre[49m[43m,[49m[43m [49m[43mpltloss[49m[43m,[49m[43m [49m[43mname_test[49m[43m)[49m

Cell [0;32mIn[4], line 22[0m, in [0;36mplotResults[0;34m(ax, ay, X, Y, model, title, pltloss, name)[0m
[1;32m     20[0m ay[38;5;241m.[39mplot(pltloss)
[1;32m     21[0m ay[38;5;241m.[39mset_title([38;5;124m"[39m[38;5;124mperte sur [39m[38;5;124m"[39m [38;5;241m+[39m name)
[0;32m---> 22[0m [43may[49m[38;5;241;43m.[39;49m[43mxlabel[49m([38;5;124m"[39m[38;5;124mepoch[39m[38;5;124m"[39m)
[1;32m     24[0m plt[38;5;241m.[39mtight_layout()

[0;31mAttributeError[0m: 'Axes' object has no attribute 'xlabel'
AttributeError: 'Axes' object has no attribute 'xlabel'

