Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig,axs = plt.subplots(2, 3,figsize=(15,8))
for i,name_train,name_test in zip ([0,1,2],fichiers_train,fichiers_test):
    train_data,train_labels = extract_data(name_train)
    test_data, test_labels = extract_data(name_test)

    model = PMC(train_data.shape[1])
    optimizer = optim.Adam(model.parameters())
    pltloss,acc = train_session(torch.FloatTensor(train_data),torch.FloatTensor(train_labels),model,loss,optimizer)
    
    titre= "PrÃ©cision ={0:5.3f} ".format(acc)
    plotResults(axs[0][i],axs[1][i],test_data, test_labels, model, titre, pltloss, name_test)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 3[0m
[1;32m      1[0m fig,axs [38;5;241m=[39m plt[38;5;241m.[39msubplots([38;5;241m2[39m, [38;5;241m3[39m,figsize[38;5;241m=[39m([38;5;241m15[39m,[38;5;241m8[39m))
[1;32m      2[0m [38;5;28;01mfor[39;00m i,name_train,name_test [38;5;129;01min[39;00m [38;5;28mzip[39m ([[38;5;241m0[39m,[38;5;241m1[39m,[38;5;241m2[39m],fichiers_train,fichiers_test):
[0;32m----> 3[0m     train_data,train_labels [38;5;241m=[39m [43mextract_data[49m[43m([49m[43mname_train[49m[43m)[49m
[1;32m      4[0m     test_data, test_labels [38;5;241m=[39m extract_data(name_test)
[1;32m      6[0m     model [38;5;241m=[39m PMC(train_data[38;5;241m.[39mshape[[38;5;241m1[39m])

Cell [0;32mIn[1], line 25[0m, in [0;36mextract_data[0;34m(filename)[0m
[1;32m     22[0m features_np [38;5;241m=[39m np[38;5;241m.[39mmatrix(features)[38;5;241m.[39mastype(np[38;5;241m.[39mfloat32)
[1;32m     24[0m labels_np [38;5;241m=[39m np[38;5;241m.[39marray(labels)[38;5;241m.[39mastype(dtype[38;5;241m=[39mnp[38;5;241m.[39muint8)
[0;32m---> 25[0m labels_onehot [38;5;241m=[39m (np[38;5;241m.[39marange([43mnum_labels[49m) [38;5;241m==[39m labels_np[:, [38;5;28;01mNone[39;00m])[38;5;241m.[39mastype(np[38;5;241m.[39mfloat32)
[1;32m     27[0m [38;5;28;01mreturn[39;00m features_np,labels_onehot

[0;31mNameError[0m: name 'num_labels' is not defined
NameError: name 'num_labels' is not defined

